name: Build Reduct Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for Release
      run: dotnet build --configuration Release --no-restore
    - name: Perform xUnit Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet to Github
      run: | 
        dotnet nuget add source --username martijnvanschie --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/martijnvanschie/index.json"
        dotnet nuget push **\*.nupkg --source "github" --skip-duplicate
