name: Build Reduct Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        VERSION_FILE_PATH: package.props
        PROJECT_FILE_PATH: Reduct.System/Reduct.System.csproj
        NUGET_SOURCE: https://nuget.pkg.github.com